{% set name = "nlohmann_json" %}
{% set version = "3.2.0" %}
{% set sha256 = "2de558ff3b3b32eebfb51cf2ceb835a0fa5170e6b8712b02be9c2c07fcfe52a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/nlohmann/json/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
      - 0001-do-not-test.patch

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/nlohmann  # [unix]
    - test -f ${PREFIX}/include/nlohmann/json.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/nlohmann_json/nlohmann_jsonConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/nlohmann_json/nlohmann_jsonTargets.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\nlohmann\json.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\nlohmann_jsonConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\nlohmann_jsonConfigVersion.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\nlohmann_jsonTargets.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/nlohmann/json
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: 'JSON for Modern C++'
  description: 'JSON for Modern C++ is a C++11 JSON parser.'
  doc_url: http://nlohmann.github.io/json/
  dev_url: http://github.com/nlohmann/json

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - gouarin
    - martinRenou
